### ISSUE TITLE
Incompatible FigureWidget with ipywidgets 8

### ISSUE THREAD

**Issue by maresb** [conda-forge/plotly-feedstock#115]
### Comment:

In light of https://github.com/plotly/plotly.py/issues/3686, I think we should add a repodata-patch to add a run_constrained of `ipywidgets <8` for all previous versions, plus the current version, and until it's solved. Do others agree?

**Comment by maresb** [comment]
And if we do this we should remove automerge until we can release the run_constrained pin.

**Comment by chohner** [comment]
Sounds good to me. According to https://github.com/plotly/plotly.py/blob/master/README.md#quickstart, we would also need lower contraints? (`"jupyterlab>=3" "ipywidgets>=7.6"`)

**Comment by maresb** [comment]
There are instructions [further down](https://github.com/plotly/plotly.py/blob/master/README.md#jupyterlab-support) on that page for `jupyterlab<3`, so I don't think we need to enforce that.

As a middle ground, how about we add a run_constrained of `ipywidgets >=7.6,<8.0` to the current recipe, but for the repodata patch only enforce `ipywidgets <8.0`? That way we move forward with enforcing the correct ipywidgets version, while doing a minimal alteration of history to prevent a real bug.

**Comment by maresb** [comment]
Closed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/365 and #116
