### ISSUE TITLE
Should we pin six or not?

### ISSUE THREAD

**Issue by maresb** [conda-forge/plotly-feedstock#94]
Continuation of the discussion from https://github.com/conda-forge/plotly-feedstock/pull/92#commitcomment-53434292

@onepunchdan:

> Does six need to be pinned to 1.15.0 when the source setup.py does not? Currently when other packages require the latest six, the conda dependency solver falls back to plotly 4.

@chohner

> I took this version pin straight from plotly's requirement.txt. I agree in that there probably isn't going to be any breakage but I haven't worked with six so I am not very comfortable making any changes here. Could you open an issue or PR to discuss?

@onepunchdan

> Ah I see. Thanks for showing me the proper location to get package requirements. The conflicting package I use is matminer which itself pins six to version 1.16.0. Given that matminer is a niche science package and has much fewer watchers/stars/forks relative to plotly, I wouldn't want to impose the minority's requirements at the risk of breakage. I'm also not in dire need of any plotly v5 functionality at the moment.

**Comment by maresb** [comment]
I have been wondering which package was responsible for the six downgrades I've been seeing lately!

I get the feeling that `requirements.txt` is less authoritative than `setup.py` since setuptools appears to not to be reading anything from `requirements.txt`. But I have asked the Plotly people directly (see issue linked directly above this comment), since I think they should be consistent.

**Comment by ocefpaf** [comment]
BTW, we no longer build anything for Python 2, so six is there probably only to satisfy the `pip check`. IMO we can try to remove it altogether.

**Comment by chohner** [comment]
Thanks for following up with plotly directly. Judging from six's [changelog](https://github.com/benjaminp/six/blob/master/CHANGES), there really shouldn't be any reason to pin to 1.15.0

**Comment by maresb** [comment]
Ok, unpinning six as in #95 should solve the issue on our side. Let's wait for https://github.com/plotly/plotly.py/issues/3167 before we remove six altogether in order to keep `pip check` happy.

**Comment by nicolaskruchten** [comment]
I don't think there's any reason to pin `six` and in any case we are planning on removing this dependency as we don't support Python 2.x in Plotly 5.x any more either :)
