### ISSUE TITLE
cannot update plotly to version 5.1.0

### ISSUE THREAD

**Issue by sleepybunn** [conda-forge/plotly-feedstock#96]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

hello, i'm still new in github, i want to report issue about updating plotly. i use it frequently, but i'm stuck in v4.14.3

i've tried :

conda install -c conda-forge plotly=5.1.0

conda install plotly=5.1.0

both were failed, solving environment was very long, and after that, message "...found conflict..." appeared

so far, only plotly has issue, the other packages (altair / pandas / geopandas / datapane / streamlit etc) work fine

OS is windows 10, python version = 3.8.10, i use spyder as daily IDE (version = 5.0.5)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by sleepybunn** [comment]
screenshot
![plotly510](https://user-images.githubusercontent.com/75115235/127770555-425ae401-1ad5-42a7-b83b-80d6e9a8c024.png)

conda is v4.10.3

**Comment by chohner** [comment]
Something from your current environment is conflicting with the new dependencies. To better investigate, the `output` of running the two commands (`conda list` and `conda info`) would be super helpful.

It should be similar to this:
```
(base) ~ ❯ conda info

     active environment : base
    active env location : /usr/local/Caskroom/miniconda/base
            shell level : 1
       user config file : /Users/usr/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/usr/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/base/envs
                          /Users/usr/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by sleepybunn** [comment]
hi chohner, thank you for your response, here is result from conda info, issue also occurs on my other laptop with windows 10

     active environment : base
    active env location : H:\ProgramData\Miniconda3
            shell level : 1
       user config file : C:\Users\yulna\.condarc
 populated config files : C:\Users\yulna\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : H:\ProgramData\Miniconda3  (writable)
      conda av data dir : H:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : H:\ProgramData\Miniconda3\pkgs
                          C:\Users\yulna\.conda\pkgs
                          C:\Users\yulna\AppData\Local\conda\conda\pkgs
       envs directories : H:\ProgramData\Miniconda3\envs
                          C:\Users\yulna\.conda\envs
                          C:\Users\yulna\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.10 Windows/7
Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

**Comment by sleepybunn** [comment]
and here is the conda list, i could not capture them all because of limitation of the miniconda prompt size...

folium                    0.12.0             pyhd8ed1ab_1    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
furl                      2.1.2              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
gdal                      3.3.0            py38hacca965_1    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
gitdb                     4.0.7              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.19             pyhd8ed1ab_0    conda-forge
glog                      0.4.0                h0174b99_3    conda-forge
glom                      20.11.0            pyhd3deb0d_0    conda-forge
gpdvega                   0.1.1rc1                 pypi_0    pypi
grpc-cpp                  1.36.4               hf620ef5_1    conda-forge
h11                       0.12.0             pyhd8ed1ab_0    conda-forge
h2                        4.0.0            py38haa244fe_3    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  0.12.3             pyhd8ed1ab_0    conda-forge
httpx                     0.16.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.6.1            py38haa244fe_0    conda-forge
importlib_metadata        4.6.1                hd8ed1ab_0    conda-forge
importlib_resources       5.2.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.0.3            py38h43734a8_0    conda-forge
ipython                   7.25.0           py38h43734a8_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.9.2              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py38haa244fe_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
keyring                   23.0.1           py38haa244fe_0    conda-forge
keyrings.alt              4.0.2              pyhd3deb0d_0    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.19.1               hbae68bd_0    conda-forge
lazy-object-proxy         1.6.0            py38h294d835_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0                     9_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_5    conda-forge
libbrotlidec              1.0.9                h8ffe710_5    conda-forge
libbrotlienc              1.0.9                h8ffe710_5    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.77.0               h789b8ee_0    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.3.0                haee3434_1    conda-forge
libglib                   2.68.3               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0                     9_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
libprotobuf               3.15.7               h7755175_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libthrift                 0.14.1               h636ae23_2    conda-forge
libtiff                   4.2.0                hc10be44_1    conda-forge
libutf8proc               2.6.1                hcb41399_0    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxgboost                1.4.0                h0e60522_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
libzip                    1.8.0                hfed4ece_0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lxml                      4.6.3            py38h292cb97_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.2              pyhd8ed1ab_0    conda-forge
mariadb                   1.0.7                    pypi_0    pypi
markupsafe                1.1.1            py38h294d835_3    conda-forge
matplotlib-base           3.4.2            py38heae8d8c_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.16           py38he774522_1
micawber                  0.5.4              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h294d835_1004    conda-forge
mkl                       2021.2.0           hb70f87d_389    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.8.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.2            py38hbd9d945_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_3    conda-forge
mysql-common              8.0.23               h57928b3_2    conda-forge
mysql-connector-python    8.0.23           py38h417165b_1    conda-forge
mysql-libs                8.0.23               hb8c0690_2    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.6.1              pyhd8ed1ab_1    conda-forge
notebook                  6.4.0              pyha770c72_0    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
opentsne                  0.6.0            py38h2f20550_1    conda-forge
orange-canvas-core        0.1.21             pyhd8ed1ab_0    conda-forge
orange-widget-base        4.13.1             pyhd8ed1ab_0    conda-forge
orange3                   3.29.3           py38h60cbd38_0    conda-forge
orange3-timeseries        0.3.10           py38haa244fe_1    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.3.1            py38h60cbd38_0    conda-forge
pandoc                    2.14.1               h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py38h9273828_1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
pluggy                    0.13.1           py38haa244fe_4    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
portpicker                1.4.0              pyhd8ed1ab_0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
posthog                   1.4.2              pyhd8ed1ab_1    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                      py_0    conda-forge
proj                      8.0.0                h1cfcee9_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
protobuf                  3.15.7           py38h885f38d_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-xgboost                1.4.0            py38haa244fe_0    conda-forge
pyarrow                   3.0.0           py38hd38ce15_10_cpu    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py38h294d835_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydantic                  1.8.2            py38h294d835_0    conda-forge
pydeck                    0.6.1              pyh44b312d_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygeos                    0.10.1           py38h13ff51f_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pylint                    2.9.5              pyhd8ed1ab_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py38h31c79cd_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.1.0            py38hf847289_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtgraph                 0.12.2             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python-slugify            5.0.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywebio                   1.3.2                    pypi_0    pypi
pywin32                   300              py38h294d835_0    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1003    conda-forge
pywinpty                  1.1.3            py38hd3f51b4_0    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.1.0           py38h09162b1_0    conda-forge
qasync                    0.17.0             pyhd8ed1ab_0    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.0              pyhd8ed1ab_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
re2                       2021.04.01           h0e60522_0    conda-forge
regex                     2021.7.6         py38h294d835_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rfc3986                   1.5.0              pyhd8ed1ab_0    conda-forge
rope                      0.19.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py38h8b54edf_2    conda-forge
ruamel_yaml               0.15.80         py38h294d835_1004    conda-forge
s3transfer                0.5.0              pyhd8ed1ab_0    conda-forge
scikit-learn              0.24.2           py38h5d5d464_0    conda-forge
scipy                     1.7.0            py38he847743_0    conda-forge
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
serverfiles               0.3.0                      py_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
shapely                   1.7.1            py38h13ff51f_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
sniffio                   1.2.0            py38haa244fe_1    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.1.1              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
spyder                    5.0.5            py38haa244fe_0    conda-forge
spyder-kernels            2.0.5            py38haa244fe_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
statsmodels               0.12.2           py38h347fdf6_0    conda-forge
streamlit                 0.80.0             pyhd8ed1ab_0    conda-forge
stringcase                1.2.0                      py_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
terminado                 0.10.1           py38haa244fe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tiledb                    2.2.9                hf84e3da_0    conda-forge
tinycss2                  1.1.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.1.0              pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.61.2             pyhd8ed1ab_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.3            py38h294d835_0    conda-forge
typing-extensions         3.10.0.0             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
ua-parser                 0.10.0                   pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     4.0.2            py38h885f38d_0    conda-forge
unidecode                 1.2.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
user-agents               2.2.0                    pypi_0    pypi
validators                0.18.2             pyhd3deb0d_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vega_datasets             0.9.0              pyhd3deb0d_0    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
watchdog                  2.1.3            py38haa244fe_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xgboost                   1.4.0            py38haa244fe_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                1.4.4              pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge

**Comment by sleepybunn** [comment]
my apologies, here is result from conda list, i exported it to .txt file with this command 

conda list --export > package-list.txt
[package-list.txt](https://github.com/conda-forge/plotly-feedstock/files/6917518/package-list.txt)

**Comment by chohner** [comment]
Can you also show the output of  `conda install -c conda-forge plotly=5.1.0`? Especially the `found conflict` part.

Generally speaking, you have probably installed a package at a specific version that is conflicting with plotly.


But the only conflict I can see right now could be `six 1.16.0`, which would have been incompatible until about 2 weeks ago (see https://github.com/conda-forge/plotly-feedstock/pull/95).

**Comment by sleepybunn** [comment]
hi chohner

the found conflict part were very long, it took hours to load

here is the example (on attached jpg), is there way to export the found conflict part to TXT file?
![foundconflict](https://user-images.githubusercontent.com/75115235/128021925-a34fc261-60e0-45c1-8702-6e797c363602.jpg)

**Comment by chohner** [comment]
Strange, these don't look to be related to plotly at all. 

I just did a quick check with the packages you mentioned and it seems like `datapane` is the offending package. Even with a new, clean environment, `datapane` will cause plotly to fall back to version 4.x:

```
> conda create --name 'plotly_test' --channel 'conda-forge' python=3.8  plotly datapane

(...)
  plotly             conda-forge/noarch::plotly-4.14.3-pyh44b312d_0
(...)
```

I checked their requirements (https://github.com/datapane/datapane/blob/master/pyproject.toml) and sure enough:

```
plotly = { version = "^4.0.0", optional = true }
```

Not sure what your options are here tbh

**Comment by maresb** [comment]
Nice detective work @chohner!

For reference, here is the datapane feedstock: https://github.com/conda-forge/datapane-feedstock/blob/master/recipe/meta.yaml which includes the corresponding `plotly >=4.0.0,<5.0.0` as a "run_constrained" dependency, meaning that Plotly is not required, but if it is installed, it must be 4.X.

**Comment by sleepybunn** [comment]
ouch, then does it mean, conflicting with datapane?

hmm, we also use datapane extensively for producing html report.

what should we do next? post a new issue on datapane feedstock? or invite datapane guy to this thread?

many thanks for nice detective work @chohner  & @maresb

**Comment by chohner** [comment]
For some (unkown) reason, the `datapane` package specifies `plotly < 5.x`, and the only people that can realistically change this are the maintainers of `datapane` itself, not of the feedstock. The feedstock is just a description of how the conda package for a particular python package will be built.

Feel free to approach them there - its rather usual to pin to a specific major version and maybe upgrading is trivial.

**Comment by sleepybunn** [comment]
ah, thanks

also i saw my workmate had posted in datapane thread, hopefully they can solve this

**Comment by chohner** [comment]
@sleepybunn I think this issue can be closed as everything concerning this feedstock is working as expected, right?
